include("ctx.jl")
include("entry.jl")
include("wildcard.jl")
include("variable.jl")
include("annotate.jl")
include("quote.jl")
include("logic.jl")
include("guard.jl")

include("collection/splat.jl")
include("collection/decons.jl")
include("collection/tuple.jl")
include("collection/vect.jl")
