struct InvalidMethodError <: Exception
end

function Base.showerror(io::IO, e::InvalidMethodError)
    print(io, "Invalid method, expect to be generated by Moshi.Data.@data")
end

invalid_method() = throw(InvalidMethodError())

variant_name(variant_instance_or_type)::Symbol = invalid_method()
variant_type(variant_instance) = invalid_method()
variant_storage(variant_instance) = invalid_method()
variant_tag(variant_instance)::UInt8 = invalid_method()

is_singleton(variant_instance_or_type)::Bool = invalid_method()
